title: Flutter Aplicado
description: Conteúdo técnico em português sobre Flutter, Dart e Material Design 3.
lang: pt-BR
theme: minima

plugins:
  - jekyll-seo-tag

header_pages:
  - index.md
  - livro.md
  - sumario.md
  - projetos.md
  - flutter/index.md
  - sobre.md

